export const BlockConstants = {
    SEED_BLOCKS: "SEED_BLOCKS",
    SET_BLOCKS: "SET_BLOCKS",
    LIGHT_UP: "LIGHT_UP",
    LIGHTS_OFF: "LIGHTS_OFF",
    CREATE_BLOCK: "CREATE_BLOCK",
    DELETE_BLOCK: "DELETE_BLOCK",
    UPDATE_BLOCK: "UPDATE_BLOCK",
    CLEAN_BLOCKS: "CLEAN_BLOCKS",
};
